framework:
    messenger:

        transports:

            kafka_consumer:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    kafka_broker: '%env(KAFKA_BROKER_LIST)%'
                    kafka_topic_prefix: '%env(KAFKA_TOPIC_PREFIX)%'
                    group_id: '%env(KAFKA_GROUP_ID)%'
                    consumer_topics:
                        - 'kafka_v1_payment'
#
#
#        routing:
#             'App\Notify\Infrastructure\Transport\KafkaMessage': async
