nelmio_api_doc:
    documentation:
        info:
            title: Payment
            description: Payment service!
            version: 1.0.0
        security:
            - bearerAuth: [ ]
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                ApiKeyAuth:
                    type: apiKey
                    in: header
                    name: X-API-Key
            schemas:
                general_error:
                    title: "General error"
                    description: "General exception"
                    type: object
                    properties:
                        errors:
                            type: array
                            items:
                                type: object
                                properties:
                                    status:
                                        type: integer
                                        readOnly: true
                                        description: Error status code
                                    title:
                                        type: string
                                        readOnly: true
                                        description: Error title
                                    details:
                                        type: string
                                        readOnly: true
                                        description: Error details
            responses:
                AccessDenied:
                    description: Access denied
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/general_error"
                Unauthorized:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/general_error"

    areas:
        path_patterns:
            - ^/api(?!/doc$)
