controllers:
    resource: ../src/Payment/Presentation/Api/v1/
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#app.swagger:
#    path: /api/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }

kernel:
    resource: ../src/Kernel.php
    type: attribute
