parameters:
    jwt.secret.key: '%env(JWT_SECRET_KEY)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true
   # _instanceof:


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Payment\Model\WritePaymentStorage:
        class: App\Payment\Infrastructure\Doctrine\Repository\PaymentRepository

    App\Payment\Application\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }



#    async.event:
#        async_bus: []

    App\Payment\Model\Event\DomainEvent: ~

#    App\Payment\Model\Event\AsyncEventCompilerPass:
#        tags:
#            - { name: async.event}

    App\Notify\Infrastructure\Transport\KafkaTransportFactory:
        tags: [messenger.transport_factory]

    React\EventLoop\StreamSelectLoop: ~
    React\EventLoop\LoopInterface: '@React\EventLoop\StreamSelectLoop'

    App\Payment\Application\Listener\ActionListener:
        arguments:
            $secretKey: '%jwt.secret.key%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 20}

#    async.eventListener:
#        class: