name: Payment

on:
  push:
    branches:
      - "main"
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install Composer Dependencies
          working-directory: ./app
          run: composer install --prefer-dist
        - name: Run Tests
          working-directory: ./app
          run: composer run-phpunit
        - name: Stat Analyze
          working-directory: ./payment
          run: composer run-psalm