name: Run Tests

on:
  push:
    branches:
      - main # измените на вашу основную ветку

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: Dockerfile # имя вашего Dockerfile

    - name: Build Docker image
      run: docker build -t my-php-app .

    - name: Run tests inside Docker container
      run: docker run my-php-app /bin/bash -c "cd /var/www/lottery && ./vendor/bin/phpunit && ./vendor/bin/psalm && ./vendor/bin/phpcs -s"
